version: '3.5'
services:
  client:
    build:
      context: .
      dockerfile: ./client/client.dockerfile
    volumes:
      - ./client:/client
      - ./communications:/client/communications
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - age_of_empires_net

  long_matches_server:
    image: rabbitmq-python-base:0.0.1
    volumes:
      - ./long_matches_server:/long_matches_server
      - ./communications:/long_matches_server/communications
    entrypoint: python3 /long_matches_server/main.py
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - age_of_empires_net

  filter_by_rating_server:
    image: rabbitmq-python-base:0.0.1
    volumes:
      - ./weaker_winner_server:/filter_by_rating
      - ./communications:/filter_by_rating/communications
    entrypoint: python3 /filter_by_rating/filter_by_rating.py
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - age_of_empires_net
    depends_on:
      - group_by_match_server

  group_by_match_server:
    image: rabbitmq-python-base:0.0.1
    volumes:
      - ./weaker_winner_server:/group_by_match
      - ./communications:/group_by_match/communications
    entrypoint: python3 /group_by_match/group_by_match.py
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - age_of_empires_net

networks:
   age_of_empires_net:
      external:
         name: age_of_empires_net