version: '3.5'
services:
  client:
    build:
      context: .
      dockerfile: ./client/client.dockerfile
    volumes:
      - ./client:/client
      - ./communications:/client/communications
      - ./config:/client/config
      - ./logger:/client/logger
    environment:
      - PYTHONUNBUFFERED=1
      - RABBITMQ_HOST=rabbitmq
      - CHUCKSIZE_IN_LINES=100
      - ENTRY_MATCH_TOKEN_INDEX=0
      - ENTRY_MATCH_AVERAGE_RATING_INDEX=5
      - ENTRY_MATCH_SERVER_INDEX=9
      - ENTRY_MATCH_DURATION_INDEX=10
      - ENTRY_MATCH_LADDER_INDEX=3
      - ENTRY_MATCH_MAP_INDEX=6
      - ENTRY_MATCH_MIRROR_INDEX=2
      - ENTRY_PLAYER_MATCH_INDEX=1
      - ENTRY_PLAYER_RATING_INDEX=2
      - ENTRY_PLAYER_WINNER_INDEX=6
      - ENTRY_PLAYER_CIV_INDEX=4
    networks:
      - age_of_empires_net
    depends_on:
      - filter_by_ladder_and_match
      - join_master_1v1
      - filter_by_rating
      - long_matches_server
      - group_by_match_master

  long_matches_server:
    image: rabbitmq-python-base:0.0.1
    volumes:
      - ./long_matches_server:/long_matches_server
      - ./communications:/long_matches_server/communications
      - ./config:/long_matches_server/config
      - ./logger:/long_matches_server/logger
    entrypoint: python3 /long_matches_server/main.py
    environment:
      - PYTHONUNBUFFERED=1
      - RABBITMQ_HOST=rabbitmq
      - MINIMUM_AVERAGE_RATING=2000
      - MINIMUM_DURATION=2
      - DURATION_FORMAT=%H:%M:%S
      - KOREA_CENTRAL_SERVER=koreacentral
      - SOUTH_EAST_ASIA_SERVER=southeastasia
      - EAST_US_SERVER=eastus
    networks:
      - age_of_empires_net

  group_by_match_master:
    image: rabbitmq-python-base:0.0.1
    volumes:
      - ./weaker_winner_server:/group_by_match
      - ./communications:/group_by_match/communications
      - ./partition_function:/group_by_match/partition_function
      - ./master_reducers_arq:/group_by_match/master_reducers_arq
      - ./config:/group_by_match/config
      - ./logger:/group_by_match/logger
    entrypoint: python3 /group_by_match/group_by_match_master.py
    environment:
      - PYTHONUNBUFFERED=1
      - RABBITMQ_HOST=rabbitmq
      - REDUCERS_AMOUNT=${REDUCERS_AMOUNT_GROUP_BY_MATCH}
      - PLAYERS_CHUNK_SIZE=100
    networks:
      - age_of_empires_net
    depends_on:
      - group_by_match_reducer

  group_by_match_reducer:
    image: rabbitmq-python-base:0.0.1
    volumes:
      - ./weaker_winner_server:/group_by_match_reducer
      - ./communications:/group_by_match_reducer/communications
      - ./master_reducers_arq:/group_by_match_reducer/master_reducers_arq
      - ./config:/group_by_match_reducer/config
      - ./logger:/group_by_match_reducer/logger
    entrypoint: python3 /group_by_match_reducer/group_by_match_reducer.py
    environment:
      - PYTHONUNBUFFERED=1
      - RABBITMQ_HOST=rabbitmq
      - MINIMUM_RATING=1000
      - MINIMUM_RATING_PORCENTAGE_DIFF=30
    networks:
      - age_of_empires_net

  filter_by_ladder_and_match:
    image: rabbitmq-python-base:0.0.1
    volumes:
      - ./filter_by_ladder_and_match:/filter_by_ladder_and_match
      - ./communications:/filter_by_ladder_and_match/communications
      - ./config:/filter_by_ladder_and_match/config
      - ./logger:/filter_by_ladder_and_match/logger
    entrypoint: python3 /filter_by_ladder_and_match/main.py
    environment:
      - PYTHONUNBUFFERED=1
      - RABBITMQ_HOST=rabbitmq
      - LADDER_1V1=RM_1v1
      - MAP_ARENA=arena
      - NO_MIRROR=False
      - LADDER_TEAM=RM_TEAM
      - MAP_ISLANDS=islands
      - OUTPUT_EXCHANGE_NAME_1V1=1v1_to_join_master_exchange
      - OUTPUT_EXCHANGE_NAME_TEAM=team_to_join_master_exchange
    networks:
      - age_of_empires_net

  join_master_1v1:
    image: rabbitmq-python-base:0.0.1
    volumes:
      - ./join_matches_and_players:/join_matches_and_players
      - ./communications:/join_matches_and_players/communications
      - ./partition_function:/join_matches_and_players/partition_function
      - ./master_reducers_arq:/join_matches_and_players/master_reducers_arq
      - ./config:/join_matches_and_players/config
      - ./logger:/join_matches_and_players/logger
    entrypoint: python3 /join_matches_and_players/master.py
    environment:
      - PYTHONUNBUFFERED=1
      - RABBITMQ_HOST=rabbitmq
      - REDUCERS_AMOUNT=${REDUCERS_AMOUNT_JOIN_1V1}
      - ROWS_CHUNK_SIZE=100
      - PLAYERS_INPUT_EXCHANGE_NAME=players_fanout_exchange
      - MATCHES_INPUT_EXCHANGE_NAME=1v1_to_join_master_exchange
      - OUTPUT_EXCHANGE_NAME=1v1_join_master_to_reducers_exchange
      - KEYS_QUEUE_NAME=1v1_join_master_to_reducers_queue
      - BARRIER_QUEUE_NAME=1v1_join_reducers_barrier
      - REDUCERS_OUTPUT_QUEUE_NAME=1v1_join_reducers_to_group_by_civ_master_queue
    networks:
      - age_of_empires_net
    depends_on:
      - join_reducer_1v1

  join_reducer_1v1:
    image: rabbitmq-python-base:0.0.1
    volumes:
      - ./join_matches_and_players:/join_matches_and_players
      - ./communications:/join_matches_and_players/communications
      - ./master_reducers_arq:/join_matches_and_players/master_reducers_arq
      - ./config:/join_matches_and_players/config
      - ./logger:/join_matches_and_players/logger
    entrypoint: python3 /join_matches_and_players/reducer.py
    environment:
      - PYTHONUNBUFFERED=1
      - RABBITMQ_HOST=rabbitmq
      - INPUT_EXCHANGE_NAME=1v1_join_master_to_reducers_exchange
      - BARRIER_QUEUE_NAME=1v1_join_reducers_barrier
      - KEYS_QUEUE_NAME=1v1_join_master_to_reducers_queue
      - OUTPUT_QUEUE_NAME=1v1_join_reducers_to_group_by_civ_master_queue
    networks:
      - age_of_empires_net

  filter_by_rating:
    image: rabbitmq-python-base:0.0.1
    volumes:
      - ./filter_by_rating:/filter_by_rating
      - ./communications:/filter_by_rating/communications
      - ./config:/filter_by_rating/config
      - ./logger:/filter_by_rating/logger
    entrypoint: python3 /filter_by_rating/main.py
    environment:
      - PYTHONUNBUFFERED=1
      - RABBITMQ_HOST=rabbitmq
      - OUTPUT_EXCHANGE_NAME=filter_by_rating_to_team_join_master_exchange
      - MIN_RATING=2000
    networks:
      - age_of_empires_net
    depends_on:
      - join_master_team

  join_master_team:
    image: rabbitmq-python-base:0.0.1
    volumes:
      - ./join_matches_and_players:/join_matches_and_players
      - ./communications:/join_matches_and_players/communications
      - ./partition_function:/join_matches_and_players/partition_function
      - ./master_reducers_arq:/join_matches_and_players/master_reducers_arq
      - ./config:/join_matches_and_players/config
      - ./logger:/join_matches_and_players/logger
    entrypoint: python3 /join_matches_and_players/master.py
    environment:
      - PYTHONUNBUFFERED=1
      - RABBITMQ_HOST=rabbitmq
      - REDUCERS_AMOUNT=${REDUCERS_AMOUNT_JOIN_TEAM}
      - ROWS_CHUNK_SIZE=100
      - PLAYERS_INPUT_EXCHANGE_NAME=filter_by_rating_to_team_join_master_exchange
      - MATCHES_INPUT_EXCHANGE_NAME=team_to_join_master_exchange
      - OUTPUT_EXCHANGE_NAME=team_join_master_to_reducers_exchange
      - KEYS_QUEUE_NAME=team_join_master_to_reducers_queue
      - BARRIER_QUEUE_NAME=team_join_reducers_barrier
      - REDUCERS_OUTPUT_QUEUE_NAME=team_join_reducers_to_group_by_civ_master_queue
    networks:
      - age_of_empires_net
    depends_on:
      - join_reducer_team

  join_reducer_team:
    image: rabbitmq-python-base:0.0.1
    volumes:
      - ./join_matches_and_players:/join_matches_and_players
      - ./communications:/join_matches_and_players/communications
      - ./master_reducers_arq:/join_matches_and_players/master_reducers_arq
      - ./config:/join_matches_and_players/config
      - ./logger:/join_matches_and_players/logger
    entrypoint: python3 /join_matches_and_players/reducer.py
    environment:
      - PYTHONUNBUFFERED=1
      - RABBITMQ_HOST=rabbitmq
      - INPUT_EXCHANGE_NAME=team_join_master_to_reducers_exchange
      - BARRIER_QUEUE_NAME=team_join_reducers_barrier
      - KEYS_QUEUE_NAME=team_join_master_to_reducers_queue
      - OUTPUT_QUEUE_NAME=team_join_reducers_to_group_by_civ_master_queue
    networks:
      - age_of_empires_net

  group_by_civ_master_1v1:
    image: rabbitmq-python-base:0.0.1
    volumes:
      - ./group_by_civ:/group_by_civ
      - ./communications:/group_by_civ/communications
      - ./partition_function:/group_by_civ/partition_function
      - ./master_reducers_arq:/group_by_civ/master_reducers_arq
      - ./config:/group_by_civ/config
      - ./logger:/group_by_civ/logger
    entrypoint: python3 /group_by_civ/master.py
    environment:
      - PYTHONUNBUFFERED=1
      - RABBITMQ_HOST=rabbitmq
      - REDUCERS_AMOUNT=${REDUCERS_AMOUNT_GROUP_BY_CIV_1V1}
      - PLAYERS_CHUNK_SIZE=100
      - PLAYERS_INPUT_QUEUE_NAME=1v1_join_reducers_to_group_by_civ_master_queue
      - OUTPUT_EXCHANGE_NAME=1v1_group_by_civ_master_to_reducers_exchange
      - KEYS_QUEUE_NAME=1v1_group_by_civ_master_to_reducers_queue
      - BARRIER_QUEUE_NAME=1v1_group_by_civ_reducers_barrier
      - REDUCERS_OUTPUT_QUEUE_NAME=1v1_group_by_civ_reducers_to_winner_rate_calculador_queue
    networks:
      - age_of_empires_net
    depends_on:
      - group_by_civ_reducer_1v1

  group_by_civ_reducer_1v1:
    image: rabbitmq-python-base:0.0.1
    volumes:
      - ./group_by_civ:/group_by_civ
      - ./communications:/group_by_civ/communications
      - ./master_reducers_arq:/group_by_civ/master_reducers_arq
      - ./config:/group_by_civ/config
      - ./logger:/group_by_civ/logger
    entrypoint: python3 /group_by_civ/count_wins_and_defeats_reducer.py
    environment:
      - PYTHONUNBUFFERED=1
      - RABBITMQ_HOST=rabbitmq
      - INPUT_EXCHANGE_NAME=1v1_group_by_civ_master_to_reducers_exchange
      - BARRIER_QUEUE_NAME=1v1_group_by_civ_reducers_barrier
      - KEYS_QUEUE_NAME=1v1_group_by_civ_master_to_reducers_queue
      - OUTPUT_QUEUE_NAME=1v1_group_by_civ_reducers_to_winner_rate_calculador_queue
    networks:
      - age_of_empires_net

  group_by_civ_master_team:
    image: rabbitmq-python-base:0.0.1
    volumes:
      - ./group_by_civ:/group_by_civ
      - ./communications:/group_by_civ/communications
      - ./partition_function:/group_by_civ/partition_function
      - ./master_reducers_arq:/group_by_civ/master_reducers_arq
      - ./config:/group_by_civ/config
      - ./logger:/group_by_civ/logger
    entrypoint: python3 /group_by_civ/master.py
    environment:
      - PYTHONUNBUFFERED=1
      - RABBITMQ_HOST=rabbitmq
      - REDUCERS_AMOUNT=${REDUCERS_AMOUNT_GROUP_BY_CIV_TEAM}
      - PLAYERS_CHUNK_SIZE=100
      - PLAYERS_INPUT_QUEUE_NAME=team_join_reducers_to_group_by_civ_master_queue
      - OUTPUT_EXCHANGE_NAME=team_group_by_civ_master_to_reducers_exchange
      - KEYS_QUEUE_NAME=team_group_by_civ_master_to_reducers_queue
      - BARRIER_QUEUE_NAME=team_group_by_civ_reducers_barrier
      - REDUCERS_OUTPUT_QUEUE_NAME=team_group_by_civ_reducers_to_top_5_calculador_queue
    networks:
      - age_of_empires_net
    depends_on:
      - group_by_civ_reducer_team

  group_by_civ_reducer_team:
    image: rabbitmq-python-base:0.0.1
    volumes:
      - ./group_by_civ:/group_by_civ
      - ./communications:/group_by_civ/communications
      - ./master_reducers_arq:/group_by_civ/master_reducers_arq
      - ./config:/group_by_civ/config
      - ./logger:/group_by_civ/logger
    entrypoint: python3 /group_by_civ/count_times_used_reducer.py
    environment:
      - PYTHONUNBUFFERED=1
      - RABBITMQ_HOST=rabbitmq
      - INPUT_EXCHANGE_NAME=team_group_by_civ_master_to_reducers_exchange
      - BARRIER_QUEUE_NAME=team_group_by_civ_reducers_barrier
      - KEYS_QUEUE_NAME=team_group_by_civ_master_to_reducers_queue
      - OUTPUT_QUEUE_NAME=team_group_by_civ_reducers_to_top_5_calculador_queue
    networks:
      - age_of_empires_net

  winner_rate_calculator:
    image: rabbitmq-python-base:0.0.1
    volumes:
      - ./civs_calculators:/winner_rate_calculator
      - ./communications:/winner_rate_calculator/communications
      - ./config:/winner_rate_calculator/config
      - ./logger:/winner_rate_calculator/logger
    entrypoint: python3 /winner_rate_calculator/winner_rate_calculator.py
    environment:
      - PYTHONUNBUFFERED=1
      - RABBITMQ_HOST=rabbitmq
      - INPUT_QUEUE_NAME=1v1_group_by_civ_reducers_to_winner_rate_calculador_queue
    networks:
      - age_of_empires_net

  top_5_times_used_calculator:
    image: rabbitmq-python-base:0.0.1
    volumes:
      - ./civs_calculators:/top_5_times_used_calculator
      - ./communications:/top_5_times_used_calculator/communications
      - ./config:/top_5_times_used_calculator/config
      - ./logger:/top_5_times_used_calculator/logger
    entrypoint: python3 /top_5_times_used_calculator/top_5_times_used_calculator.py
    environment:
      - PYTHONUNBUFFERED=1
      - RABBITMQ_HOST=rabbitmq
      - INPUT_QUEUE_NAME=team_group_by_civ_reducers_to_top_5_calculador_queue
    networks:
      - age_of_empires_net

networks:
   age_of_empires_net:
      external:
         name: age_of_empires_net