version: '3.5'
services:
  client:
    build:
      context: .
      dockerfile: ./client/client.dockerfile
    volumes:
      - ./client:/client
      - ./communications:/client/communications
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - age_of_empires_net
    depends_on:
      - filter_by_ladder_and_match
      - join_master_1v1
      - join_master_team
      - long_matches_server
      - group_by_match_master

  long_matches_server:
    image: rabbitmq-python-base:0.0.1
    volumes:
      - ./long_matches_server:/long_matches_server
      - ./communications:/long_matches_server/communications
    entrypoint: python3 /long_matches_server/main.py
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - age_of_empires_net

  group_by_match_master:
    image: rabbitmq-python-base:0.0.1
    volumes:
      - ./weaker_winner_server:/group_by_match
      - ./communications:/group_by_match/communications
      - ./partition_function:/group_by_match/partition_function
      - ./master_reducers_arq:/group_by_match/master_reducers_arq
    entrypoint: python3 /group_by_match/group_by_match_master.py
    environment:
      - PYTHONUNBUFFERED=1
      - REDUCERS_AMOUNT=${REDUCERS_AMOUNT}
    networks:
      - age_of_empires_net
    depends_on:
      - group_by_match_reducer

  group_by_match_reducer:
    image: rabbitmq-python-base:0.0.1
    volumes:
      - ./weaker_winner_server:/group_by_match_reducer
      - ./communications:/group_by_match_reducer/communications
      - ./master_reducers_arq:/group_by_match_reducer/master_reducers_arq
    entrypoint: python3 /group_by_match_reducer/group_by_match_reducer.py
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - age_of_empires_net

  filter_by_ladder_and_match:
    image: rabbitmq-python-base:0.0.1
    volumes:
      - ./filter_by_ladder_and_match:/filter_by_ladder_and_match
      - ./communications:/filter_by_ladder_and_match/communications
    entrypoint: python3 /filter_by_ladder_and_match/main.py
    environment:
      - PYTHONUNBUFFERED=1
      - OUTPUT_EXCHANGE_NAME_1V1=1v1_to_join_master_exchange
      - OUTPUT_EXCHANGE_NAME_TEAM=team_to_join_master_exchange
    networks:
      - age_of_empires_net

  join_master_1v1:
    image: rabbitmq-python-base:0.0.1
    volumes:
      - ./join_matches_and_players:/join_matches_and_players
      - ./communications:/join_matches_and_players/communications
      - ./partition_function:/join_matches_and_players/partition_function
      - ./master_reducers_arq:/join_matches_and_players/master_reducers_arq
    entrypoint: python3 /join_matches_and_players/master.py
    environment:
      - PYTHONUNBUFFERED=1
      - REDUCERS_AMOUNT=${REDUCERS_AMOUNT}
      - MATCHES_INPUT_EXCHANGE_NAME=1v1_to_join_master_exchange
      - OUTPUT_EXCHANGE_NAME=1v1_join_master_to_reducers_exchange
      - KEYS_QUEUE_NAME=1v1_join_master_to_reducers_queue
      - BARRIER_QUEUE_NAME=1v1_join_reducers_barrier
      - REDUCERS_OUTPUT_QUEUE_NAME=1v1_join_reducers_to_group_by_civ_master_queue
    networks:
      - age_of_empires_net
    depends_on:
      - join_reducer_1v1

  join_reducer_1v1:
    image: rabbitmq-python-base:0.0.1
    volumes:
      - ./join_matches_and_players:/join_matches_and_players
      - ./communications:/join_matches_and_players/communications
      - ./master_reducers_arq:/join_matches_and_players/master_reducers_arq
    entrypoint: python3 /join_matches_and_players/reducer.py
    environment:
      - PYTHONUNBUFFERED=1
      - INPUT_EXCHANGE_NAME=1v1_join_master_to_reducers_exchange
      - BARRIER_QUEUE_NAME=1v1_join_reducers_barrier
      - KEYS_QUEUE_NAME=1v1_join_master_to_reducers_queue
      - OUTPUT_QUEUE_NAME=1v1_join_reducers_to_group_by_civ_master_queue
    networks:
      - age_of_empires_net

  join_master_team:
    image: rabbitmq-python-base:0.0.1
    volumes:
      - ./join_matches_and_players:/join_matches_and_players
      - ./communications:/join_matches_and_players/communications
      - ./partition_function:/join_matches_and_players/partition_function
      - ./master_reducers_arq:/join_matches_and_players/master_reducers_arq
    entrypoint: python3 /join_matches_and_players/master.py
    environment:
      - PYTHONUNBUFFERED=1
      - REDUCERS_AMOUNT=${REDUCERS_AMOUNT}
      - MATCHES_INPUT_EXCHANGE_NAME=team_to_join_master_exchange
      - OUTPUT_EXCHANGE_NAME=team_join_master_to_reducers_exchange
      - KEYS_QUEUE_NAME=team_join_master_to_reducers_queue
      - BARRIER_QUEUE_NAME=team_join_reducers_barrier
      - REDUCERS_OUTPUT_QUEUE_NAME=team_join_reducers_to_group_by_civ_master_queue
    networks:
      - age_of_empires_net
    depends_on:
      - join_reducer_team

  join_reducer_team:
    image: rabbitmq-python-base:0.0.1
    volumes:
      - ./join_matches_and_players:/join_matches_and_players
      - ./communications:/join_matches_and_players/communications
      - ./master_reducers_arq:/join_matches_and_players/master_reducers_arq
    entrypoint: python3 /join_matches_and_players/reducer.py
    environment:
      - PYTHONUNBUFFERED=1
      - INPUT_EXCHANGE_NAME=team_join_master_to_reducers_exchange
      - BARRIER_QUEUE_NAME=team_join_reducers_barrier
      - KEYS_QUEUE_NAME=team_join_master_to_reducers_queue
      - OUTPUT_QUEUE_NAME=team_join_reducers_to_group_by_civ_master_queue
    networks:
      - age_of_empires_net

  group_by_civ_master_1v1:
    image: rabbitmq-python-base:0.0.1
    volumes:
      - ./group_by_civ:/group_by_civ
      - ./communications:/group_by_civ/communications
      - ./partition_function:/group_by_civ/partition_function
      - ./master_reducers_arq:/group_by_civ/master_reducers_arq
    entrypoint: python3 /group_by_civ/master.py
    environment:
      - PYTHONUNBUFFERED=1
      - REDUCERS_AMOUNT=${REDUCERS_AMOUNT}
      - PLAYERS_INPUT_QUEUE_NAME=1v1_join_reducers_to_group_by_civ_master_queue
      - OUTPUT_EXCHANGE_NAME=1v1_group_by_civ_master_to_reducers_exchange
      - KEYS_QUEUE_NAME=1v1_group_by_civ_master_to_reducers_queue
      - BARRIER_QUEUE_NAME=1v1_group_by_civ_reducers_barrier
      - REDUCERS_OUTPUT_QUEUE_NAME=1v1_group_by_civ_reducers_to_winner_rate_calculador_queue
    networks:
      - age_of_empires_net
    depends_on:
      - group_by_civ_reducer_1v1

  group_by_civ_reducer_1v1:
    image: rabbitmq-python-base:0.0.1
    volumes:
      - ./group_by_civ:/group_by_civ
      - ./communications:/group_by_civ/communications
      - ./master_reducers_arq:/group_by_civ/master_reducers_arq
    entrypoint: python3 /group_by_civ/count_wins_and_defeats_reducer.py
    environment:
      - PYTHONUNBUFFERED=1
      - INPUT_EXCHANGE_NAME=1v1_group_by_civ_master_to_reducers_exchange
      - BARRIER_QUEUE_NAME=1v1_group_by_civ_reducers_barrier
      - KEYS_QUEUE_NAME=1v1_group_by_civ_master_to_reducers_queue
      - OUTPUT_QUEUE_NAME=1v1_group_by_civ_reducers_to_winner_rate_calculador_queue
    networks:
      - age_of_empires_net

  group_by_civ_master_team:
    image: rabbitmq-python-base:0.0.1
    volumes:
      - ./group_by_civ:/group_by_civ
      - ./communications:/group_by_civ/communications
      - ./partition_function:/group_by_civ/partition_function
      - ./master_reducers_arq:/group_by_civ/master_reducers_arq
    entrypoint: python3 /group_by_civ/master.py
    environment:
      - PYTHONUNBUFFERED=1
      - REDUCERS_AMOUNT=${REDUCERS_AMOUNT}
      - PLAYERS_INPUT_QUEUE_NAME=team_join_reducers_to_group_by_civ_master_queue
      - OUTPUT_EXCHANGE_NAME=team_group_by_civ_master_to_reducers_exchange
      - KEYS_QUEUE_NAME=team_group_by_civ_master_to_reducers_queue
      - BARRIER_QUEUE_NAME=team_group_by_civ_reducers_barrier
      - REDUCERS_OUTPUT_QUEUE_NAME=team_group_by_civ_reducers_to_top_5_calculador_queue
    networks:
      - age_of_empires_net
    depends_on:
      - group_by_civ_reducer_team

  group_by_civ_reducer_team:
    image: rabbitmq-python-base:0.0.1
    volumes:
      - ./group_by_civ:/group_by_civ
      - ./communications:/group_by_civ/communications
      - ./master_reducers_arq:/group_by_civ/master_reducers_arq
    entrypoint: python3 /group_by_civ/count_times_used_reducer.py
    environment:
      - PYTHONUNBUFFERED=1
      - INPUT_EXCHANGE_NAME=team_group_by_civ_master_to_reducers_exchange
      - BARRIER_QUEUE_NAME=team_group_by_civ_reducers_barrier
      - KEYS_QUEUE_NAME=team_group_by_civ_master_to_reducers_queue
      - OUTPUT_QUEUE_NAME=team_group_by_civ_reducers_to_top_5_calculador_queue
    networks:
      - age_of_empires_net

  winner_rate_calculator:
    image: rabbitmq-python-base:0.0.1
    volumes:
      - ./civs_calculators:/winner_rate_calculator
      - ./communications:/winner_rate_calculator/communications
    entrypoint: python3 /winner_rate_calculator/winner_rate_calculator.py
    environment:
      - PYTHONUNBUFFERED=1
      - INPUT_QUEUE_NAME=1v1_group_by_civ_reducers_to_winner_rate_calculador_queue
    networks:
      - age_of_empires_net

  top_5_times_used_calculator:
    image: rabbitmq-python-base:0.0.1
    volumes:
      - ./civs_calculators:/top_5_times_used_calculator
      - ./communications:/top_5_times_used_calculator/communications
    entrypoint: python3 /top_5_times_used_calculator/top_5_times_used_calculator.py
    environment:
      - PYTHONUNBUFFERED=1
      - INPUT_QUEUE_NAME=team_group_by_civ_reducers_to_top_5_calculador_queue
    networks:
      - age_of_empires_net

networks:
   age_of_empires_net:
      external:
         name: age_of_empires_net