version: '3.5'
services:
  rabbitmq:
    build:
      context: ./rabbitmq
      dockerfile: rabbitmq.dockerfile
    ports:
      - 15672:15672
    healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:15672"]
        interval: 10s
        timeout: 5s
        retries: 10
    networks:
      - age_of_empires_net

networks:
  age_of_empires_net:
    name: age_of_empires_net
    ipam:
      driver: default
      config:
        - subnet: 174.25.125.0/24