RABBITMQ_HOST = 'rabbitmq' # TODO envvar

STRING_ENCODING = 'utf-8'
STRING_LINE_SEPARATOR = '\n'
STRING_COLUMN_SEPARATOR = ', '

MATCHES_IDS_SEPARATOR = ', '
CLIENT_TO_LONG_MATCHES_QUEUE_NAME = 'client_to_long_matches'
LONG_MATCHES_TO_CLIENT_QUEUE_NAME = 'long_matches_to_client'
SENTINEL_MESSAGE = "SENTINEL"
